# -*- coding: utf-8 -*-
"""Entrena.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14pEyu5UhHe9DCNToHQu2VUZEHsl2o4A0
"""

# ============================================================
# Clasificacion de tickets con MLflow
# ============================================================

# 1. Instalacion de librerias
!pip install -q datasets pandas scikit-learn mlflow matplotlib seaborn pyngrok

# 2. Importar librerias
import os
import mlflow
import mlflow.sklearn
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from datasets import load_dataset

from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

# 3. Crear carpetas
os.makedirs("data", exist_ok=True)
os.makedirs("results", exist_ok=True)
os.makedirs("artifacts", exist_ok=True)

# 4. Configurar MLflow local
import os
import shutil

os.environ["MLFLOW_ALLOW_FILE_STORE"] = "true"

if os.path.exists("mlruns"):
    shutil.rmtree("mlruns")

mlflow.set_tracking_uri("file:./mlruns")
mlflow.set_experiment("clasificacion_tickets_soporte")

# 5. Cargar dataset
datos = load_dataset("Tobi-Bueck/customer-support-tickets")
datos = datos["train"]

tabla = datos.to_pandas()

# 6. Guardar una muestra del dataset
tabla.head(1000).to_csv("data/muestra_tickets.csv", index=False)

# 7. Limpieza basica
tabla = tabla[tabla["language"] == "en"].copy()

tabla["subject"] = tabla["subject"].fillna("")
tabla["body"] = tabla["body"].fillna("")
tabla["queue"] = tabla["queue"].fillna("unknown")

tabla["texto"] = tabla["subject"].astype(str) + ". " + tabla["body"].astype(str)

tabla = tabla[tabla["texto"].str.len() > 10]

# 8. Usar una muestra para que corra mas rapido
tabla = tabla.sample(n=min(3000, len(tabla)), random_state=42)

# 9. Variables del modelo
x = tabla["texto"]
y = tabla["queue"]

# 10. Grafica de categorias
plt.figure(figsize=(10, 5))
tabla["queue"].value_counts().plot(kind="bar")
plt.title("Distribucion de tickets por categoria")
plt.xlabel("Categoria")
plt.ylabel("Cantidad")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.savefig("artifacts/distribucion_categorias.png")
plt.show()

# 11. Grafica de longitud de texto
tabla["longitud_texto"] = tabla["texto"].str.len()

plt.figure(figsize=(8, 5))
plt.hist(tabla["longitud_texto"], bins=30)
plt.title("Longitud de los tickets")
plt.xlabel("Longitud")
plt.ylabel("Cantidad")
plt.tight_layout()
plt.savefig("artifacts/longitud_tickets.png")
plt.show()

# 12. Separar datos
x_entrenamiento, x_prueba, y_entrenamiento, y_prueba = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# 13. Validacion cruzada
validacion = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=42
)

# 14. Funcion para entrenar y guardar en MLflow
def entrenar_y_guardar(nombre_modelo, proceso, parametros):

    busqueda = GridSearchCV(
        estimator=proceso,
        param_grid=parametros,
        cv=validacion,
        scoring="f1_macro",
        n_jobs=-1
    )

    with mlflow.start_run(run_name=nombre_modelo):

        busqueda.fit(x_entrenamiento, y_entrenamiento)

        mejor_modelo = busqueda.best_estimator_
        predicciones = mejor_modelo.predict(x_prueba)

        accuracy = accuracy_score(y_prueba, predicciones)
        precision = precision_score(y_prueba, predicciones, average="macro", zero_division=0)
        recall = recall_score(y_prueba, predicciones, average="macro", zero_division=0)
        f1 = f1_score(y_prueba, predicciones, average="macro", zero_division=0)

        try:
            probas = mejor_modelo.predict_proba(x_prueba)
            roc_auc = roc_auc_score(
                y_prueba,
                probas,
                multi_class="ovr",
                average="macro"
            )
        except:
            roc_auc = 0

        reporte = classification_report(
            y_prueba,
            predicciones,
            zero_division=0,
            output_dict=True
        )

        reporte_tabla = pd.DataFrame(reporte).transpose()
        ruta_reporte = "artifacts/reporte_" + nombre_modelo + ".csv"
        reporte_tabla.to_csv(ruta_reporte)

        matriz = confusion_matrix(y_prueba, predicciones)

        plt.figure(figsize=(10, 8))
        sns.heatmap(matriz, cmap="Blues")
        plt.title("Matriz de confusion - " + nombre_modelo)
        plt.xlabel("Prediccion")
        plt.ylabel("Real")
        plt.tight_layout()

        ruta_matriz = "artifacts/matriz_" + nombre_modelo + ".png"
        plt.savefig(ruta_matriz)
        plt.show()

        mlflow.log_param("modelo", nombre_modelo)
        mlflow.log_params(busqueda.best_params_)

        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision_macro", precision)
        mlflow.log_metric("recall_macro", recall)
        mlflow.log_metric("f1_macro", f1)
        mlflow.log_metric("roc_auc_macro", roc_auc)

        mlflow.log_artifact(ruta_reporte)
        mlflow.log_artifact(ruta_matriz)
        mlflow.log_artifact("artifacts/distribucion_categorias.png")
        mlflow.log_artifact("artifacts/longitud_tickets.png")

        mlflow.sklearn.log_model(mejor_modelo, "modelo")

        print("\nModelo:", nombre_modelo)
        print("Mejores parametros:", busqueda.best_params_)
        print("Accuracy:", accuracy)
        print("Precision:", precision)
        print("Recall:", recall)
        print("F1:", f1)
        print("ROC-AUC:", roc_auc)

        return {
            "modelo": nombre_modelo,
            "accuracy": accuracy,
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "roc_auc": roc_auc,
            "mejores_parametros": str(busqueda.best_params_)
        }

# 15. Modelo 1: Regresion Logistica
proceso_logistica = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("modelo", LogisticRegression(max_iter=1000))
])

parametros_logistica = {
    "tfidf__max_features": [3000, 5000],
    "modelo__C": [0.1, 1, 10]
}

# 16. Modelo 2: Random Forest
proceso_bosque = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("modelo", RandomForestClassifier(random_state=42))
])

parametros_bosque = {
    "tfidf__max_features": [3000, 5000],
    "modelo__n_estimators": [100, 200],
    "modelo__max_depth": [None, 20]
}

# 17. Entrenar modelos
resultados = []

resultados.append(
    entrenar_y_guardar(
        "Regresion_Logistica",
        proceso_logistica,
        parametros_logistica
    )
)

resultados.append(
    entrenar_y_guardar(
        "Random_Forest",
        proceso_bosque,
        parametros_bosque
    )
)

# 18. Tabla final
tabla_resultados = pd.DataFrame(resultados)
display(tabla_resultados)

tabla_resultados.to_csv("results/resultados_mlflow.csv", index=False)

# 19. Grafica comparativa
plt.figure(figsize=(8, 5))
tabla_resultados.set_index("modelo")[["accuracy", "precision", "recall", "f1", "roc_auc"]].plot(kind="bar")
plt.title("Comparacion de modelos")
plt.ylabel("Valor")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("results/comparacion_modelos.png")
plt.show()

# 20. Mostrar mensaje final
print("Proceso terminado")
print("Se guardaron metricas, parametros y artefactos en MLflow")
print("Tambien se guardaron archivos en data, results y artifacts")